### ISSUE TITLE
Relative mountpoint in compose file

### ISSUE THREAD

**Issue by Flying--Dutchman** [MatchbookLab/local-persist#78]
Is it possible to use relative paths in the docker-compose.yaml file?
So, something like:

```
version: '3' 
  services:  
    mariadb:  
        image: 'mariadb'  
        container_name: mariadb1
        environment:
            - MYSQL_DATABASE=default
        volumes:
            - data-volume:/var/lib/mysql
volumes:
   data-volume:
        driver: local-persist
        driver_opts:
            mountpoint: ./mariadb
```

When I execute `docker-compose up .`, I'm getting following error:

> ERROR: for mariadb  Cannot start service mariadb: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/run/containerd/io.containerd.runtime.v1.linux/moby/db5c3688b835f041024a9982ec4e0d3ad8fe2f5e13a3514b410a6db74938f5a9/mariadb\\\" to rootfs \\\"/var/lib/docker/overlay2/598a206cbdf4c4a99ed293eaf7fbca8a67b61beddb901ce646a2265580bf758d/merged\\\" at \\\"/var/lib/mysql\\\" caused \\\"stat /run/containerd/io.containerd.runtime.v1.linux/moby/db5c3688b835f041024a9982ec4e0d3ad8fe2f5e13a3514b410a6db74938f5a9/mariadb: no such file or directory\\\"\"": unknown

EDIT:
local-persist was installed using the "Quick way", with the install script in README.
