### ISSUE TITLE
docker-compose v3 example

### ISSUE THREAD

**Issue by joepagan** [MatchbookLab/local-persist#81]
Hey,

I'm trying to share the same volume over multiple services and [found a suggestion](https://stackoverflow.com/questions/42232051/docker-compose-volumes-from-equivalent-with-version-3) that in v3 we need to use this docker plugin.

I see from your readme we wont be able to install the plugin on macos, so, it will need to be setup as a container though I am unsure how to succesfully accomplish this can you clarify this for me?

The readme suggests a `docker run` command, though this seems like a lenghty step which will need to be customised & run for each app we want to work with, is there a way to just have the app-specific docker-compose handle that step too? Or will that not be possible as the docker-compose.yml will have no idea what `loca-persist` driver is at that point?

Example of what I want 
```yml
version: "3.8"
services:
    php-fpm:
      build:
        context: ./
        dockerfile: ./docker/development/config/php-fpm.dockerfile
      networks:
        - app
      ports:
        - 9000:9000
      volumes:
        - php-fpm:/var/www/html
      env_file: .env.dev
    nginx:
      build:
        context: ./
        dockerfile: ./docker/development/config/nginx.dockerfile
      ports:
        - 80:80
      networks:
        - app
      volumes:
        - php-fpm:/var/www/html
    driver-persist:
      image: cwspear/docker-local-persist-volume-plugin
      volumes:
        - /run/docker/plugins/:/run/docker/plugins/
        - ./json:/var/lib/docker/plugin-data/ \
        - ./:/var/www/html
volumes:
  mysqldata:
  php-fpm:
    driver: local-persist
    driver_opts:
      mountpoint: ./
networks:
  app:
    driver: bridge
```

error when I try run:

```sh
Creating volume "docker3-test_php-fpm" with local-persist driver
ERROR: Volume php-fpm specifies nonexistent driver local-persist
```
