### ISSUE TITLE
Error: no such file or directory: unknown

### ISSUE THREAD

**Issue by weisiqian** [MatchbookLab/local-persist#84]
1. First step:

install the plugin

```
docker run -d  -v /run/docker/plugins/:/run/docker/plugins/ -v U:/docker/plugin/local-persist/path/to/store/json/for/restart/:/var/lib/docker/plugin-data/ -v U:/docker/common/data:/data  cwspear/docker-local-persist-volume-plugin 
```

2. Second Step

```
docker-compose -f .\docker-compose\mysql.yml up -d
```

here is the mysql.yml.

```
# mysql.yml
version: "3"
services:
  common-data:
    image: ubuntu:latest
    container_name: common-data
    restart: always
    privileged: true
    entrypoint: /bin/bash
    stdin_open: true
    tty: true
    volumes:
      # - "U:/docker/common/data:/data"
      # - "U:/docker/common/mysql:/var/lib/mysql"
      - "common-data:/data"
      # - "common-data:/var/lib/mysql"
  mysql:
    image: mysql:5.7.26
    ports:
      - "3306:3306"
    container_name: mysql
    restart: always
    privileged: true
    command:
      --character-set-server=utf8
      --lower_case_table_names=1
    volumes:
      - "common-data:/data"
      # - "common-data:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
volumes:
  common-data:
    # external: true
    driver: local-persist
    driver_opts:
      mountpoint: U:/docker/common/data
```

then i got this Error

![image](https://user-images.githubusercontent.com/19994951/137426142-4e30117d-816c-4e3a-b3ff-4e4647122213.png)

actually, that folder is  exist

![image](https://user-images.githubusercontent.com/19994951/137426268-96b019bb-c198-4319-a542-9dad9f5d4e4e.png)

![image](https://user-images.githubusercontent.com/19994951/137426339-b188328a-e1c8-4f69-b9f1-c7508a3c1a92.png)

docker info

![image](https://user-images.githubusercontent.com/19994951/137426592-2a58819c-b7f0-4acb-aa2d-827e995b60fe.png)

docker-compose version

```
docker-compose version 1.29.2, build 5becea4c
```

system is windows 10

![image](https://user-images.githubusercontent.com/19994951/137426674-69a40508-9dab-47f5-9024-f79d715390af.png)

help
